### ISSUE TITLE
Error: missing info in rstudio/rstudioapi/bugfix/api-theme-colors

### ISSUE THREAD

**Issue by SteadyGiant** [ginolhac/upnews#10]
Here's what I see when I launch the add-in on Windows:

![image](https://user-images.githubusercontent.com/9023041/67017215-6bd83380-f0c7-11e9-9a8d-b0a9560f5747.png)

I'm using the latest version of `upnews`, 0.1.2. I forced a reinstall but got the same error afterwards. All other packages and RStudio are up-to-date, as of today. RStudio (for Windows) version is 1.2.5001.

**Comment by ginolhac** [comment]
Hello,
thanks for reporting, I think it might be related to #9 . I will have a look.
Thanks again,

**Comment by ginolhac** [comment]
that worked me, please reopen if the new version doesn't solve it for you.
thanks again !

**Comment by SteadyGiant** [comment]
Works for me. Thank you very much.
